if(EXISTS "C:/Users/yagiz/Desktop/Project/smart-maintenance-suite/build_win/src/tests/utility/utility_tests[1]_tests.cmake")
  include("C:/Users/yagiz/Desktop/Project/smart-maintenance-suite/build_win/src/tests/utility/utility_tests[1]_tests.cmake")
else()
  add_test(utility_tests_NOT_BUILT utility_tests_NOT_BUILT)
endif()
